services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=archive'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    networks:
      - data

  keycloak:
    image: 'quay.io/keycloak/keycloak:23.0.3'
    container_name: keycloak
    command: start-dev --import-realm
    volumes:
      - ../platform/keycloak:/opt/keycloak/data/import
    environment:
      - 'KEYCLOAK_ADMIN=user'
      - 'KEYCLOAK_ADMIN_PASSWORD=password'
    ports:
      - '9090:8080'

networks:
  data:
    driver: bridge